name: 'Simple Vercel Deploy'
description: 'Deploy to Vercel'
inputs:
  github-token:
    description: 'github token'
    required: true
  vercel-token:
    description: 'vercel token'
    required: true
  vercel-org-id:
    description: 'vercel team / personal id'
    required: true
  vercel-project-id:
    description: 'vercel project id'
    required: true
  is-production:
    description: 'production flag'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'cloud-lightning'
  color: 'yellow'
